"""empty message

Revision ID: 49d6f14d8923
Revises: e182b32c2fc2
Create Date: 2026-04-04 00:09:13.782372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d6f14d8923'
down_revision: Union[str, Sequence[str], None] = 'e182b32c2fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users MODIFY COLUMN role ENUM('student', 'tutor', 'admin')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users MODIFY COLUMN role ENUM('student', 'tutor')")
    # ### end Alembic commands ###
