"""Refactor to O2M tutor subjects

Revision ID: bd7f059a698d
Revises: d478e66ae9df
Create Date: 2026-04-04 15:51:13.647888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd7f059a698d'
down_revision: Union[str, Sequence[str], None] = 'd478e66ae9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    try:
        op.drop_table('tutor_subjects')
    except Exception:
        pass
        
    try:
        op.drop_table('subjects')
    except Exception:
        pass

    # Recreate the correct O2M table
    op.create_table('tutor_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tutor_profile_id'], ['tutor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_subjects_id'), 'tutor_subjects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_subjects', sa.Column('subject_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tutor_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('tutor_subjects_ibfk_2'), 'tutor_subjects', 'tutor_profiles', ['tutor_profile_id'], ['id'])
    op.create_foreign_key(op.f('tutor_subjects_ibfk_1'), 'tutor_subjects', 'subjects', ['subject_id'], ['id'])
    op.drop_index(op.f('ix_tutor_subjects_id'), table_name='tutor_subjects')
    op.drop_column('tutor_subjects', 'name')
    op.drop_column('tutor_subjects', 'id')
    op.create_table('subjects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    # ### end Alembic commands ###
